server/corpsoftportal/authapp/urls.py
from django.urls import path
from . import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', authapp.main, name='main')

]

server/corpsoftportal/corpsoftportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('softwareapp.urls')),
    path('warehouse', include('warehouseapp.urls')),
    path('accounts/', include('authapp.urls')),

]

server/corpsoftportal/softwareapp/urls.py
from django.urls import path
from softwareapp import views as sofwareapp

app_name = 'softwareapp'

urlpatterns = [
    path('catalog_soft', sofwareapp.catalog_soft, name='catalog_soft'),
    path('category_creation', sofwareapp.category_create, name='category_creation'),
    path('software_creation', sofwareapp.software_create, name='software_creation'),
    path('transfer_creation', sofwareapp.transfer_create, name='transfer_creation'),
    path('reciever', sofwareapp.reciever, name='reciever'),
    path('software_details/<int:software_id>', sofwareapp.software_details, name='software_details'),
    path('category_details/<str:category_name>', sofwareapp.category_details, name='category_details'),
    path('check_warehouse', sofwareapp.check_warehouse, name='check_warehouse'),
    path('get_warehouse', sofwareapp.get_warehouse, name='get_warehouse'),
    path('', sofwareapp.main, name='main'),
]

server/corpsoftportal/softwareapp/models.py
from django.db import models
from warehouseapp.models import Warehouse


# Create your models here.
class LicenseType(models.Model):
    """class license type"""
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Типы лицензий"
        verbose_name_plural = "Типы лицензий"

    def __str__(self):
        return self.name


class LicenseTerm(models.Model):
    name = models.CharField(max_length=32)
    """class license term"""
    class Meta:
        verbose_name = "Срок действия лицензии"
        verbose_name_plural = "Срок действия лицензии"

    def __str__(self):
        return self.name


class Category(models.Model):
    """software category model class"""
    name = models.CharField(max_length=128)
    license_type = models.ForeignKey(
        LicenseType, verbose_name='Тип лицензии', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Software(models.Model):
    """software class"""
    class Meta:
        verbose_name = "Софт"
        verbose_name_plural = "Софт"

    name = models.CharField("Название", max_length=128)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE, blank=True)
    license_term = models.ForeignKey(LicenseTerm, verbose_name='Срок лицензии', on_delete=models.CASCADE, blank=True)
    license_key = models.TextField("Лицензионный ключ", max_length=128, blank=True)
    # 3 - склад нераспределенного ПО
    owner = models.ForeignKey(Warehouse, verbose_name='Владелец', on_delete=models.CASCADE, default=3)

    def __str__(self):
        return self.name


class Transfer(models.Model):
    """class transfer"""
    source = models.ForeignKey(Warehouse, related_name='sender', on_delete=models.CASCADE, verbose_name='Отправитель')
    destination = models.ForeignKey(Warehouse, related_name='reciever', on_delete=models.CASCADE, verbose_name='Получатель')
    software = models.ForeignKey(Software, verbose_name='Передаваемый софт', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Проводка"
        verbose_name_plural = "Проводки"

server/corpsoftportal/softwareapp/forms.py
from django import forms
from softwareapp.models import Category, Software, Transfer


class CategoryCreateForm(forms.ModelForm):
    class Meta:
       model = Category
       fields = ('name', 'license_type')

    def __init__(self, *args, **kwargs):
        super(CategoryCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class SofwareForm(forms.ModelForm):
    class Meta:
        model = Software
        fields = ('name', 'category', 'license_term', 'owner', 'license_key')

    def __init__(self, *args, **kwargs):
        super(SofwareForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class TransferCreateForm(forms.ModelForm):
    class Meta:
        model = Transfer
        fields = ('source', 'destination', 'software')

    def __init__(self, *args, **kwargs):
        super(TransferCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class SearchWarehouseForm(forms.Form):
    warehouse = forms.CharField(label='Введите имя компьютера')

server/corpsoftportal/softwareapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from softwareapp.models import Category, LicenseType, Software, LicenseTerm, Transfer
from softwareapp.forms import CategoryCreateForm, SofwareForm, TransferCreateForm, SearchWarehouseForm
from warehouseapp.models import Warehouse, WarehouseType
import json


# Create your views here.

@login_required
def main(request):
    """Основная страница
    Выводится список проблем, на которые стоит обратить внимание"""
    unknown_owner = Software.objects.filter(owner=Warehouse.objects.get(name='Нераспределенное ПО').id)
    unknown_category = Software.objects.filter(category=Category.objects.get(name='Unknown').id)

    content = {
        'unknown_owner': unknown_owner,
        'unknown_category': unknown_category
    }
    return render(request, 'softwareapp/base.html', content)


@login_required
def catalog_soft(request):
    """Страница каталога"""
    categories = Category.objects.all()

    content = {
        'categories': categories
    }

    return render(request, 'softwareapp/catalog_soft.html', content)


@login_required
def category_create(request):
    title = 'Создание категории'
    # Вывод формы для редактирования
    if request.method == "POST":
        form = CategoryCreateForm(request.POST)
        if form.is_valid():
            category = Category(name=request.POST['name'],
                                license_type=LicenseType.objects.get(id=request.POST['license_type']))
            category.save()
            return HttpResponseRedirect(reverse('softwareapp:main'))
    else:
        form = CategoryCreateForm()

    content = {
        'title': title,
        'form': form
    }

    return render(request, 'softwareapp/category_creation.html', content)


@login_required
def software_create(request):
    title = 'Создание категории'
    # Вывод формы для редактирования
    if request.method == "POST":
        form = SofwareForm(request.POST)
        if form.is_valid():
            software = Software(name=request.POST['name'],
                                category=Category.objects.get(id=request.POST['category']),
                                license_term=LicenseTerm.objects.get(id=request.POST['license_term']),
                                license_key=request.POST['license_key'])
            software.save()

            return HttpResponseRedirect(reverse('softwareapp:main'))
    else:
        form = SofwareForm()

    content = {
        'title': title,
        'form': form
    }

    return render(request, 'softwareapp/software_creation.html', content)


@login_required
def transfer_create(request):
    title = 'Проводка'
    # Вывод формы для редактирования
    if request.method == "POST":
        form = TransferCreateForm(request.POST)
        if form.is_valid():
            software = Software.objects.get(id=request.POST['software'])
            software.owner = Warehouse.objects.get(id=request.POST['destination'])
            software.save()

            return HttpResponseRedirect(reverse('softwareapp:main'))
    else:
        form = TransferCreateForm()

    content = {
        'title': title,
        'form': form
    }

    return render(request, 'softwareapp/transfer_creation.html', content)


@csrf_exempt
def reciever(request):
    """Обработчик данных с хостов
    После приема данных требуется вручную расставить категории.
    После создания каталога софта эта проблема уйдет"""
    if request.method == "POST":
        data = json.loads(json.loads(request.body))
        if not Warehouse.objects.get(name=data['machine_name']).exists():
            host = Warehouse(name=data['machine_name'], warehouse_type=WarehouseType.objects.get(id=2))
            host.save()

        for software in data['soft']:
            if not Software.objects.get(name=software['DisplayName'],
                                        owner_id=Warehouse.objects.get(name=data['machine_name'])).exists():
                if software['DisplayName'] == '':
                    continue
                software_name = Software(name=software['DisplayName'],
                                         owner_id=Warehouse.objects.get(name=data['machine_name']).id,
                                         category_id=Category.objects.get(name='Unknown').id,
                                         license_term_id=LicenseTerm.objects.get(name='Unknown').id)
                software_name.save()

    return render(request, 'softwareapp/base.html', {})


def software_details(request, software_id):
    """Изменение записи софта"""
    instance = Software.objects.get(id=software_id)

    #Вывод формы для редактирования
    if request.method == "POST":
        form = SofwareForm(request.POST, instance=instance)
        if form.is_valid():
            instance.category_id = Category.objects.get(id=request.POST['category'])
            instance.license_term = LicenseTerm.objects.get(id=request.POST['license_term'])
            instance.owner = Warehouse.objects.get(id=request.POST['owner'])
            instance.license_key = request.POST['license_key']
            instance.save()
            return HttpResponseRedirect(reverse('softwareapp:main'))

    else:
        form = SofwareForm(instance=instance)

    content = {
        'itm': instance,
        'form': form
    }
    return render(request, 'softwareapp/detail.html', content)


@login_required
def category_details(request, category_name):
    """Каталог софта внутри категории"""
    soft = Software.objects.filter(category=Category.objects.get(name=category_name))
    content = {
        'soft': soft,
        'category': category_name
    }
    return render(request, 'softwareapp/category_detail.html', content)


@login_required
def check_warehouse(request):
    """Форма поиска склада"""
    form = SearchWarehouseForm()
    return render(request, 'softwareapp/check_warehouse.html', {'form': form})


# @login_required
def get_warehouse(request):
    """Список софта на указанном складе"""
    warehouse = request.POST['warehouse']
    try:
        soft = Software.objects.filter(owner=Warehouse.objects.get(name=warehouse))
        content = {
            'soft': soft,
            'category': warehouse
        }
        return render(request, 'softwareapp/category_detail.html', content)
    except:
        return HttpResponseRedirect(reverse('softwareapp:check_warehouse'))

server/corpsoftportal/templates/softwareapp/base.html
{%  load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
            {{ title|capfirst }}
    {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'softwareapp/css/style.css' %}"/>

</head>

<body>
    <div class="container">
        <div class="header">
            {% block menu %}
                {% include 'softwareapp/includes/inc_menu.html' %}
            {% endblock %}
        </div>
            {% block inc_menu %}
            {% endblock %}


    {% block content %}
        <h2>Проблемы</h2>
        Список полученного платного ПО, который не назначен для установки на указанный компьютер
        <div class="product_catalog">
        <h2>Требуется проставить владельца</h2>
            <table class="output">
                <tr>
                   <td><b>Softname</b></td>
                </tr>
                {% for itm in unknown_owner %}
                <tr>
                   <td>{{ itm.name }}</td>
                </tr>
                {% endfor %}
            </table>

        <h2>Требуется классифицировать</h2>
            <table class="output">
                <tr>
                   <td><b>Softname ID</b></td>
                   <td><b>Softname</b></td>
                   <td><b>Owner</b></td>
               </tr>
                {% for itm in unknown_category %}
                <tr>
                   <td class="id"><a href="{% url 'softwareapp:software_details' itm.id %}">{{ itm.id }}</a></td>
                   <td>{{ itm.name }}</td>
                   <td>{{ itm.owner }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endblock %}
    </div>
</body>
</html>

server/corpsoftportal/templates/softwareapp/catalog_soft.html
{% extends 'softwareapp/base.html' %}


{% load static %}


{% block page_title %}
Каталог софта
{% endblock %}

{% block inc_menu %}
    {% include 'softwareapp/includes/inc_menu_soft_catalog.html' %}
{% endblock %}


{% block content %}
<h2>Категории</h2>

<div class="product_catalog">

            <ul>
                {% for itm in categories %}

                <li>
                        {{ itm.name }}
                </li>
                {% endfor %}

            </ul>
        </div>

<h2>Софт</h2>

<div class="product_catalog">

            <ul>
                {% for itm in software %}

                <li>
                        {{ itm.name }}
                </li>
                {% endfor %}

            </ul>
        </div>

{% endblock %}

server/corpsoftportal/templates/softwareapp/category_creation.html
{% extends 'softwareapp/base.html' %}
{% load static %}

{% block title %}

{% endblock %}


{% block content %}
    <h2>Создание новой категории софта</h2>
    <form class="form-horizontal" action="{% url 'softwareapp:category_creation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
{% endblock %}

server/corpsoftportal/templates/softwareapp/category_detail.html
{% extends 'softwareapp/base.html' %}


{% load static %}


{% block page_title %}
{{ category }}
{% endblock %}

{% block inc_menu %}
    {% include 'softwareapp/includes/inc_menu_soft_catalog.html' %}
{% endblock %}


{% block content %}

<h2>{{ category }}</h2>

<div class="product_catalog">

            <ul>
                {% for itm in soft %}

                <li>
                        {{ itm.name }}
                </li>
                {% endfor %}

            </ul>
        </div>

{% endblock %}

server/corpsoftportal/templates/softwareapp/check_warehouse.html
{% extends 'softwareapp/base.html' %}


{% load static %}


{% block page_title %}
Поиск
{% endblock %}

{% block inc_menu %}
    {% include 'softwareapp/includes/inc_menu_soft_catalog.html' %}
{% endblock %}


{% block content %}

<form  class="form-horizontal" action="{% url 'softwareapp:get_warehouse'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
{% endblock %}

server/corpsoftportal/templates/softwareapp/detail.html
{% extends 'softwareapp/base.html' %}

{% load static %}

{% block title %}

{% endblock %}

{% block inc_menu %}
    {% include 'softwareapp/includes/inc_menu_soft_catalog.html' %}
{% endblock %}


{% block content %}
<h2>Изменение {{ itm.name }}</h2>
    <form class="form-horizontal" action="{% url 'softwareapp:software_details' itm.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
{% endblock %}

server/corpsoftportal/templates/softwareapp/software_creation.html
{% extends 'softwareapp/base.html' %}
{% load static %}

{% block title %}

{% endblock %}


{% block content %}
    <h2>Создание нового объекта</h2>
    <form class="form-horizontal" action="{% url 'softwareapp:software_creation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
{% endblock %}

server/corpsoftportal/templates/softwareapp/transfer_creation.html
{% extends 'softwareapp/base.html' %}
{% load static %}

{% block title %}

{% endblock %}


{% block content %}
    <h2>Проводка</h2>
    <form class="form-horizontal" action="{% url 'softwareapp:transfer_creation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
{% endblock %}