server/corpsoftportal/authapp/urls.py
from django.urls import path
from . import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', authapp.main, name='main')

]

server/corpsoftportal/corpsoftportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('softwareapp.urls')),
    path('warehouse', include('warehouseapp.urls')),
    path('accounts/', include('authapp.urls')),

]

server/corpsoftportal/authapp/models.py
from django.db import models

# Create your models here.

server/corpsoftportal/authapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

server/corpsoftportal/authapp/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import LoginForm
from django.contrib import auth
from ldap3 import Server, Connection, NTLM
from django.contrib.auth.models import User


# Create your views here.
def main(request):
    return render(request, 'authapp/base.html', {})


def login(request):
    login_form = LoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('softwareapp:main'))

    content = {
        'login_form': login_form
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('softwareapp:main'))

server/corpsoftportal/templates/authapp/base.html
{% extends 'softwareapp/base.html' %}
{% load staticfiles %}
    {%  block menu %}

    {%  endblock %}

{% block content %}

{% endblock %}

server/corpsoftportal/templates/authapp/login.html
{%  extends 'softwareapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form class="form-horizontal" action="{% url 'authapp:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Войти">
    </form>

{% endblock %}