server/corpsoftportal/authapp/urls.py
from django.urls import path
from . import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', authapp.main, name='main')

]

server/corpsoftportal/corpsoftportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('softwareapp.urls')),
    path('warehouse', include('warehouseapp.urls')),
    path('accounts/', include('authapp.urls')),

]

server/corpsoftportal/warehouseapp/urls.py
from django.urls import path
from warehouseapp import views as warehouseapp

app_name = 'warehouseapp'

urlpatterns = [
    path('warehouse_creation', warehouseapp.warehouse_create, name='warehouse_create'),
    path('', warehouseapp.main, name='main'),
]

server/corpsoftportal/warehouseapp/models.py
from django.db import models
from django.apps import apps
# from softwareapp.models import Software
# # Create your models here.
# Software = apps.get_model('sofwareapp', 'Software')

class WarehouseType(models.Model):
    """class license type"""
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name = "Тип склада"
        verbose_name_plural = "Типы складов"

    def __str__(self):
        return self.name


class Warehouse(models.Model):
    """class license type"""
    name = models.CharField(verbose_name='Название склада', max_length=128)
    warehouse_type = models.ForeignKey(
        WarehouseType, verbose_name='Тип склада', on_delete=models.CASCADE, blank=True)
    class Meta:
        verbose_name = "Склад"
        verbose_name_plural = "Склады"

    def __str__(self):
        return self.name

server/corpsoftportal/warehouseapp/forms.py
from django import forms
from warehouseapp.models import Warehouse


class WarehouseCreateForm(forms.ModelForm):
    class Meta:
       model = Warehouse
       fields = ('name', 'warehouse_type')

    def __init__(self, *args, **kwargs):
        super(WarehouseCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

server/corpsoftportal/warehouseapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from warehouseapp.models import Warehouse, WarehouseType
from warehouseapp.forms import WarehouseCreateForm
# Create your views here.


@login_required
def main(request):
    return render(request, 'warehouseapp/base.html', {})


@login_required
def warehouse_create(request):
    title = 'Создание склада'
    # Вывод формы для редактирования
    if request.method == "POST":
        form = WarehouseCreateForm(request.POST)
        if form.is_valid():
            warehouse = Warehouse(name=request.POST['name'], warehouse_type=WarehouseType.objects.get(id=request.POST['warehouse_type']))
            warehouse.save()
            return HttpResponseRedirect(reverse('warehouseapp:main'))
    else:
        form = WarehouseCreateForm()

    content = {
        'title': title,
        'form': form
    }

    return render(request, 'warehouseapp/warehouse_creation.html', content)

server/corpsoftportal/templates/warehouseapp/base.html
{%  load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
            {{ title|capfirst }}
    {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'softwareapp/css/style.css' %}"/>

</head>

<body>
    <div class="container">
        <div class="header">
            {% block menu %}
                {% include 'softwareapp/includes/inc_menu.html' %}
            {% endblock %}
        </div>
        <hr>
            {% block inc_menu %}
                {% include 'warehouseapp/includes/inc_menu.html' %}
            {% endblock %}


    {% block content %}

    {% endblock %}
    </div>
</body>
</html>

server/corpsoftportal/templates/warehouseapp/warehouse_creation.html
{% extends 'warehouseapp/base.html' %}
{% load static %}

{% block title %}

{% endblock %}


{% block content %}
    <h2>Создание нового склада</h2>
    <form class="form-horizontal" action="{% url 'warehouseapp:warehouse_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
{% endblock %}